site:
  title: Kubewarden documentation
  start_page: 1.16@kubewarden-product-docs::index.adoc

content:
  sources:
    - url: https://github.com/rancher/longhorn-product-docs.git
      branches: [1.16, 1.15, 1.14, 1.13]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  attributes:
    page-pagination: ''
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build/site
